name: translatable
version: 1.2.0
author: Dan Parnham <dan@emergent-design.co.uk>
homepage: https://github.com/emergent-design/translatable
description: >-
  Generate translatable getters/functions that are mapped to allow
  remote storage and modification of translations.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
