name: translatable
version: 1.0.1
author: Dan Parnham <dan@emergent-design.co.uk>
homepage: https://github.com/emergent-design/translatable
description: >-
  Generate translatable getters/functions that are mapped to allow
  remote storage and modification of translations.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^1.1.6
  analyzer: ^0.35.4
  source_gen: ^0.9.4+4

dev_dependencies:
  build_runner: ^1.6.7
